---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: jtate-vault-talk
  path: "./apps"
  prune: true
  wait: true
  timeout: 5m
  retryInterval: 1m
  dependsOn:
    - name: helmresources
  postBuild:
    substitute:
      ENVIRONMENT: "dev"
      NAMESPACE_PREFIX: "dev"
      CLUSTER_NAME: "vault-talk"
      DOMAIN: "vault-talk.lan"
      VAULT_URL: "http://dev-vault.dev-vault.svc.cluster.local:8200"
